version: '3'
services:
  web:
    build: .
    ports:
      - "9292:9292"
    ports:
      - port=9393
  db:
    image: postgres:9.5.9
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=app
      - RAILS_ENV=production
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
